name = "gpack"
version = "0.1.0"

gleam = ">= 1.5.0"

description = "A MessagePack encoder/decoder for Gleam"
licences = ["GPL-3.0-or-later"]
repository = { type = "github", user = "l-x", repo = "gpack" }
links = [{ title = "MessagePack", href = "https://msgpack.org/" }]

internal_modules = []

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
